version: '3.8'

services:

  postgres:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_DB: credito_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - credito-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - credito-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - credito-network

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: sh
    command:
      - -c
      - >
        sleep 15 &&
        kafka-topics --bootstrap-server kafka:29092
        --create
        --topic credito-consultado
        --partitions 1
        --replication-factor 1
        --if-not-exists
    networks:
      - credito-network
    restart: "no"

  backend:
    build:
      context: ./credito-constituido-consulta-api
    container_name: credito_backend
    restart: on-failure
    environment:
      DATA_SOURCE_URL: jdbc:postgresql://postgres:5432/credito_db
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: admin
      SERVER_PORT: 8081
      KAFKA_SERVER: kafka:29092
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - credito-network

  frontend:
    build:
      context: ./credito-constituido-consulta-app
    container_name: credito_frontend
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - credito-network

volumes:
  postgres_data:

networks:
  credito-network:
    driver: bridge
